### ISSUE TITLE
How about adding comments ? 

### ISSUE THREAD

**Issue by virgile-dev** [jpmvferreira/espanso-mega-pack#7]
```
- trigger: ":comment:" 
replace: "[//]: # (content)"
```

**Comment by jpmvferreira** [comment]
Is this for the markdown package? Because if so, I've already added a comment trigger in the previous update:
```
- trigger: ":comment:"
  label: "Markdown - Comment"
  replace: "<!--- $|$ -->"
  force_clipboard: true
```

Also, I'm unfamiliar with this syntax, is that another way to make comments in markdown?

**Comment by jpmvferreira** [comment]
Well I'm closing this issue because it seems stale. If you have anything else to say feel free to re-open it.
